apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: nodejs

spec:
  replicas: 2

  selector:
    matchLabels:
      app: nodejs-app

  template:
    metadata:
      labels:
        app: nodejs-app

    spec:
      containers:
      - name: nodejs-app

        image: 617998378772.dkr.ecr.us-east-1.amazonaws.com/cuer_assign/nodjs-app:latest

        imagePullPolicy: Always

        ports:
        - containerPort: 3000
      
      env:
        - name: PORT
          value: "3000"

        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_HOST

        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_NAME

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 10
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 20
          periodSeconds: 20
